version: "3.7"
services:
  server:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    hostname: server
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  db:
    image: postgres:10
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db