version: "3.7"
services:
  server:
    build: ./server/
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "9090:9090"
    hostname: server
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trade-history
  db:
    image: postgres:10
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trade-history